### ISSUE TITLE
Set up coverity scan in CI

### ISSUE THREAD

**Issue by thedrow** [c9s/r3#110]
Right now I'm scanning the code manually but we can use the coverity scan plugin to submit the builds periodically.
coverity scan can find errors other linters can't.

**Comment by bjosv** [comment]
We could register the project to [Coverity Scan](https://scan.coverity.com/faq) for free since r3 uses the MIT license.
The registration step takes some time since they seem to do a manual review for the approval.
@c9s If you also think this would be useful then I could prepare the registration, and prepare a PR for the Github Action job running it.
